//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantProje.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RestaurantEntities1 : DbContext
    {
        public RestaurantEntities1()
            : base("name=RestaurantEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminGiri> AdminGiris { get; set; }
        public virtual DbSet<Menü> Menü { get; set; }
        public virtual DbSet<MusteriGiri> MusteriGiris { get; set; }
        public virtual DbSet<Personel> Personels { get; set; }
        public virtual DbSet<Rezervasyon> Rezervasyons { get; set; }
        public virtual DbSet<Sipari> Siparis { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int MenuEkleYenile(Nullable<int> menuNo, string yemekAdi, Nullable<int> yemekFiyati, string icecekAdi, Nullable<int> icecekFiyati, string tatliAdi, Nullable<int> tatliFiyati)
        {
            var menuNoParameter = menuNo.HasValue ?
                new ObjectParameter("MenuNo", menuNo) :
                new ObjectParameter("MenuNo", typeof(int));
    
            var yemekAdiParameter = yemekAdi != null ?
                new ObjectParameter("YemekAdi", yemekAdi) :
                new ObjectParameter("YemekAdi", typeof(string));
    
            var yemekFiyatiParameter = yemekFiyati.HasValue ?
                new ObjectParameter("YemekFiyati", yemekFiyati) :
                new ObjectParameter("YemekFiyati", typeof(int));
    
            var icecekAdiParameter = icecekAdi != null ?
                new ObjectParameter("IcecekAdi", icecekAdi) :
                new ObjectParameter("IcecekAdi", typeof(string));
    
            var icecekFiyatiParameter = icecekFiyati.HasValue ?
                new ObjectParameter("IcecekFiyati", icecekFiyati) :
                new ObjectParameter("IcecekFiyati", typeof(int));
    
            var tatliAdiParameter = tatliAdi != null ?
                new ObjectParameter("TatliAdi", tatliAdi) :
                new ObjectParameter("TatliAdi", typeof(string));
    
            var tatliFiyatiParameter = tatliFiyati.HasValue ?
                new ObjectParameter("TatliFiyati", tatliFiyati) :
                new ObjectParameter("TatliFiyati", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MenuEkleYenile", menuNoParameter, yemekAdiParameter, yemekFiyatiParameter, icecekAdiParameter, icecekFiyatiParameter, tatliAdiParameter, tatliFiyatiParameter);
        }
    
        public virtual ObjectResult<MenuListele_Result> MenuListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MenuListele_Result>("MenuListele");
        }
    
        public virtual int MenuSil(Nullable<int> menuNo)
        {
            var menuNoParameter = menuNo.HasValue ?
                new ObjectParameter("MenuNo", menuNo) :
                new ObjectParameter("MenuNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MenuSil", menuNoParameter);
        }
    
        public virtual ObjectResult<MenuSirala_Result> MenuSirala(Nullable<int> menuNo)
        {
            var menuNoParameter = menuNo.HasValue ?
                new ObjectParameter("MenuNo", menuNo) :
                new ObjectParameter("MenuNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MenuSirala_Result>("MenuSirala", menuNoParameter);
        }
    
        public virtual int PersonelEkleYenile(Nullable<int> personelNo, string unvan, Nullable<int> yas, string adSoyad, string adres, string telefon, Nullable<decimal> maas)
        {
            var personelNoParameter = personelNo.HasValue ?
                new ObjectParameter("PersonelNo", personelNo) :
                new ObjectParameter("PersonelNo", typeof(int));
    
            var unvanParameter = unvan != null ?
                new ObjectParameter("Unvan", unvan) :
                new ObjectParameter("Unvan", typeof(string));
    
            var yasParameter = yas.HasValue ?
                new ObjectParameter("Yas", yas) :
                new ObjectParameter("Yas", typeof(int));
    
            var adSoyadParameter = adSoyad != null ?
                new ObjectParameter("AdSoyad", adSoyad) :
                new ObjectParameter("AdSoyad", typeof(string));
    
            var adresParameter = adres != null ?
                new ObjectParameter("Adres", adres) :
                new ObjectParameter("Adres", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var maasParameter = maas.HasValue ?
                new ObjectParameter("Maas", maas) :
                new ObjectParameter("Maas", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PersonelEkleYenile", personelNoParameter, unvanParameter, yasParameter, adSoyadParameter, adresParameter, telefonParameter, maasParameter);
        }
    
        public virtual ObjectResult<PersonelListele_Result> PersonelListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PersonelListele_Result>("PersonelListele");
        }
    
        public virtual ObjectResult<PersonelSirala_Result> PersonelSirala(Nullable<int> personelNo)
        {
            var personelNoParameter = personelNo.HasValue ?
                new ObjectParameter("PersonelNo", personelNo) :
                new ObjectParameter("PersonelNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PersonelSirala_Result>("PersonelSirala", personelNoParameter);
        }
    
        public virtual int PSil(Nullable<int> personelNo)
        {
            var personelNoParameter = personelNo.HasValue ?
                new ObjectParameter("PersonelNo", personelNo) :
                new ObjectParameter("PersonelNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PSil", personelNoParameter);
        }
    
        public virtual int RezervasyonEkleYenile(Nullable<int> rezervasyonNo, Nullable<int> masaNo, string kisiAdSoyad, Nullable<int> kisiSayisi, string gelecegiSaat, string telefon)
        {
            var rezervasyonNoParameter = rezervasyonNo.HasValue ?
                new ObjectParameter("RezervasyonNo", rezervasyonNo) :
                new ObjectParameter("RezervasyonNo", typeof(int));
    
            var masaNoParameter = masaNo.HasValue ?
                new ObjectParameter("MasaNo", masaNo) :
                new ObjectParameter("MasaNo", typeof(int));
    
            var kisiAdSoyadParameter = kisiAdSoyad != null ?
                new ObjectParameter("KisiAdSoyad", kisiAdSoyad) :
                new ObjectParameter("KisiAdSoyad", typeof(string));
    
            var kisiSayisiParameter = kisiSayisi.HasValue ?
                new ObjectParameter("KisiSayisi", kisiSayisi) :
                new ObjectParameter("KisiSayisi", typeof(int));
    
            var gelecegiSaatParameter = gelecegiSaat != null ?
                new ObjectParameter("GelecegiSaat", gelecegiSaat) :
                new ObjectParameter("GelecegiSaat", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RezervasyonEkleYenile", rezervasyonNoParameter, masaNoParameter, kisiAdSoyadParameter, kisiSayisiParameter, gelecegiSaatParameter, telefonParameter);
        }
    
        public virtual ObjectResult<RezervasyonListele_Result> RezervasyonListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RezervasyonListele_Result>("RezervasyonListele");
        }
    
        public virtual int RezervasyonSil(Nullable<int> rezervasyonNo)
        {
            var rezervasyonNoParameter = rezervasyonNo.HasValue ?
                new ObjectParameter("RezervasyonNo", rezervasyonNo) :
                new ObjectParameter("RezervasyonNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RezervasyonSil", rezervasyonNoParameter);
        }
    
        public virtual ObjectResult<RezervasyonSirala_Result> RezervasyonSirala(Nullable<int> rezervasyonNo)
        {
            var rezervasyonNoParameter = rezervasyonNo.HasValue ?
                new ObjectParameter("RezervasyonNo", rezervasyonNo) :
                new ObjectParameter("RezervasyonNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RezervasyonSirala_Result>("RezervasyonSirala", rezervasyonNoParameter);
        }
    
        public virtual int SiparisEkleYenile(Nullable<int> siparisNo, string yemekAdi, string icecekAdi, string tatliAdi)
        {
            var siparisNoParameter = siparisNo.HasValue ?
                new ObjectParameter("SiparisNo", siparisNo) :
                new ObjectParameter("SiparisNo", typeof(int));
    
            var yemekAdiParameter = yemekAdi != null ?
                new ObjectParameter("YemekAdi", yemekAdi) :
                new ObjectParameter("YemekAdi", typeof(string));
    
            var icecekAdiParameter = icecekAdi != null ?
                new ObjectParameter("IcecekAdi", icecekAdi) :
                new ObjectParameter("IcecekAdi", typeof(string));
    
            var tatliAdiParameter = tatliAdi != null ?
                new ObjectParameter("TatliAdi", tatliAdi) :
                new ObjectParameter("TatliAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SiparisEkleYenile", siparisNoParameter, yemekAdiParameter, icecekAdiParameter, tatliAdiParameter);
        }
    
        public virtual ObjectResult<SiparisListele_Result> SiparisListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SiparisListele_Result>("SiparisListele");
        }
    
        public virtual int SiparisSil(Nullable<int> siparisNo)
        {
            var siparisNoParameter = siparisNo.HasValue ?
                new ObjectParameter("SiparisNo", siparisNo) :
                new ObjectParameter("SiparisNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SiparisSil", siparisNoParameter);
        }
    
        public virtual ObjectResult<SiparisSirala_Result> SiparisSirala(Nullable<int> siparisNo)
        {
            var siparisNoParameter = siparisNo.HasValue ?
                new ObjectParameter("SiparisNo", siparisNo) :
                new ObjectParameter("SiparisNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SiparisSirala_Result>("SiparisSirala", siparisNoParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
