//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervasyon
    {
        public int RezervasyonNo { get; set; }
        public Nullable<int> MasaNo { get; set; }
        public string KisiAdSoyad { get; set; }
        public Nullable<int> KisiSayisi { get; set; }
        public string GelecegiSaat { get; set; }
        public string Telefon { get; set; }
    }
}
